version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      DB_HOST: db
      DB_DATABASE: trading
      DB_USERNAME: root
      DB_PASSWORD: secret
    working_dir: /var/www
    depends_on:
      - db
      - webserver
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: trading-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: trading-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: trading
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql
    volumes:
      -   tradingdata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  tradingdata:
    driver: local
